#! /usr/bin/python
from argparse import ArgumentParser
import json
from src.python.runner import run


def main():
    parser = ArgumentParser()
    parser.add_argument('-f', metavar='json', nargs='*', type=file)
    parser.add_argument('-t', metavar='timelimit', type=int)
    parser.add_argument('-m', metavar='memorylimit', type=int)
    parser.add_argument('-c', metavar='cores', type=int)
    parser.add_argument('-p', metavar='phrase', nargs='*', type=str)
    args = parser.parse_args()

    result = []
    for conffile in args.f:
        config = json.load(conffile)
        for seed in config['sourceSeeds']:
            result.append(run('./solution.exe', config, seed))
    print json.dumps(result)


if __name__ == '__main__':
    main()